version: '3'
services:
  server:
    image: clintam/shortly
    build: .
    command: server
    ports:
    - 8080:8080
  redis:
    image: redis:3.0.7
    ports:
     - 6379:6379
    volumes:
    - db:/data
volumes:
  db: